### ISSUE TITLE
Issues Found by Rosario 

### ISSUE THREAD

**Issue by mrjacopong** [mrjacopong/electromagnetic-compatibility#1]
1. nell'equazione 1.5 viene ripetuto due volte il dy

2. pagina 14 accanto a T dovrebbe starci period credo
![8BB7AC88-BC2F-4A96-90A5-0B1CE6EAD3E2](https://user-images.githubusercontent.com/45855823/116707712-47089000-a9cf-11eb-992e-90f422c00efe.jpeg)

3. pagina 15 e poi 16 nell'equazione 2.16 ci sta la seconda parentesi tonda con la ripetizione di t1 e z1 mentre il prof ha messo t2, z2
![4A7D22E2-193F-4F5C-BBF8-23A7DDC3767D](https://user-images.githubusercontent.com/45855823/116707839-67384f00-a9cf-11eb-94ce-037a0d160fcb.jpeg)

4. pagina 17 qui è proprio un dubbio perchè riguardando la lezione lui dice che k*r è una plane wave, mentre kr (senza il prodotto scalare ha la forma di una sfera)
se vuoi ricontrolllare lo dice proprio gli ultimi minuti della lezione del 26/02
![DF028C41-E4CE-4D5E-9B6B-FCD8057BC147](https://user-images.githubusercontent.com/45855823/116707945-81722d00-a9cf-11eb-8210-46093ebc79e3.jpeg)

**Comment by roslaroc** [comment]
5. pag 20: wave equation (3.14 e 3.15) il segno è + e non - (video lezione  1/03 minuto 50)
![image](https://user-images.githubusercontent.com/16683342/117011667-56991900-acee-11eb-98a0-64478e77b3ad.png)

6. equazione 3.24: manca il dw al termine dell'integrale

7. eq. 3.33: unità di misura w/m^2

8. esercizio pag 36 la f=100 e non 10

9. eq 5.22: alla fine il segno è + e non -
![image](https://user-images.githubusercontent.com/16683342/117012233-053d5980-acef-11eb-816f-e15a1c5a3669.png)

10. pag 40: l in cm e non metri

11. eq. 5.26: nel secondo esponenziale il - è un +
![image](https://user-images.githubusercontent.com/16683342/117012637-72e98580-acef-11eb-9b22-f684bd95412d.png)

12. eq. 5.30: non + ma -
![image](https://user-images.githubusercontent.com/16683342/117012808-97456200-acef-11eb-9d5f-0cd78aef54f9.png)

13. eq. 6.2: primo esponenziale manca un - essendo una direct wave
![image](https://user-images.githubusercontent.com/16683342/117013134-e095b180-acef-11eb-9bee-c568d35edd60.png)

14. eq. 6.15: invertiti i max e min.... Zmax= Vmax/Imin e Zmin=Vmin/Imax
![image](https://user-images.githubusercontent.com/16683342/117013344-10dd5000-acf0-11eb-920f-f17d94c97505.png)

15. eq. 7.10: manca il quadrato al modulo di Vg
![image](https://user-images.githubusercontent.com/16683342/117013566-47b36600-acf0-11eb-8a6b-a1cd85e42e17.png)

16. eq. 8.2: in Etheta non è 2pi ma 4pi
![image](https://user-images.githubusercontent.com/16683342/117013747-6dd90600-acf0-11eb-92f3-2dccc4973732.png)

17. eq: 8.6: nell'ultimo passaggio manca il sin(theta)dtheta

18. eq. 8.8: nella parte immaginaria Io e pi sono elevati alla seconda
![image](https://user-images.githubusercontent.com/16683342/117014030-b1337480-acf0-11eb-9756-9bc5d7f7142e.png)

**Comment by roslaroc** [comment]
19. pag 4: errori unità di misura
H [A/m]
D[C/m^2]

20. eq. 1.7: manca il dV
![image](https://user-images.githubusercontent.com/16683342/117109019-4e8bb880-ad84-11eb-88eb-5577b7d91b0c.png)

21. eq. 1.14: manca il - su d/dt
![image](https://user-images.githubusercontent.com/16683342/117110642-bd6a1100-ad86-11eb-966f-89d00cd93310.png)

22. eq. 1.21: qui non dovrebbe essere il teorema della divergenza? intendo dire che i calcoli mi sembrano giusti ma c'è scritto stokes
![image](https://user-images.githubusercontent.com/16683342/117112764-d7f1b980-ad89-11eb-89f6-1f422937ed04.png)

23. dubbio eq. 3.8: il rotore di E non dovrebbe poi essere - jw B? 
![image](https://user-images.githubusercontent.com/16683342/117152093-fb345d00-adb9-11eb-97e8-a977612b72d8.png)

24. dubbio eq. 22: E funzione di E,t?? penso possa essere funzione di r,t
![image](https://user-images.githubusercontent.com/16683342/117207816-ad891600-adf4-11eb-9224-6d9a6ee0774d.png)

25. eq. 5.1: controllo del risultato della derivata.
![image](https://user-images.githubusercontent.com/16683342/117275111-004ae800-ae5e-11eb-804a-f326fdcf26c8.png)
.
26. eq. 8.3: dubbio sull'assenza di k (da riguardare le lezioni del prof

27. tra i parametri dell'antenna penso manchi il gain. G=Po/Pl= (Po/Pa)*(Pa/Pl)=D*delta

28. credo ci sia un'inversione di Jwc e Jwl 
![image](https://user-images.githubusercontent.com/16683342/117534652-adef0000-aff2-11eb-9ede-92e9f1586211.png)

29. eq. 5.13: credo ci siano errori nei segni
![image](https://user-images.githubusercontent.com/16683342/117535542-8c901300-aff6-11eb-9165-877ec77769c9.png)

**Comment by mrjacopong** [comment]
9- non mi trovo d'accordo con la correzione che hai fatto, il prodotto tra j*j=-1
12- in equazione 5.11 è stato spiegato a come arrivare a quell'equazione, e c'è il più
25- non ho capito cosa stai chiedendo, però effettivamente la derivata di v(z) è già stata vista nell'equazione dei telegrafisti. bisognerebbe parlarne un po' meglio a voce
26- confermo il tuo dubbio, ci vuole la k
![image](https://user-images.githubusercontent.com/45855823/117590283-fe6b7800-b12e-11eb-9a87-4e19c27ce2fd.png)

tutto il resto è stato corretto

**Comment by roslaroc** [comment]
30. eq.1.8: da riguardare bene perchè non mi torna il risultato del det
![image](https://user-images.githubusercontent.com/16683342/117934910-71c5e300-b303-11eb-998e-2e7009a4fc04.png)
31. da controllare il numero in entrambe le equazioni, penso sia sbagliato
![image](https://user-images.githubusercontent.com/16683342/117952353-64195900-b315-11eb-81ba-b2ac177b3a72.png)

**Comment by mrjacopong** [comment]
> 30. eq.1.8: da riguardare bene perchè non mi torna il risultato del det
>    ![image](https://user-images.githubusercontent.com/16683342/117934910-71c5e300-b303-11eb-998e-2e7009a4fc04.png)
> 31. da controllare il numero in entrambe le equazioni, penso sia sbagliato
>    ![image](https://user-images.githubusercontent.com/16683342/117952353-64195900-b315-11eb-81ba-b2ac177b3a72.png)

corretti entrambi, per la 31 ho controllato dal libro:
![image](https://user-images.githubusercontent.com/45855823/117958715-962db980-b31b-11eb-95d8-a1bc814aa7ad.png)

Per favore quando puoi controlla la mia risposta riguardo i punti 9-10-11 per i quali non mi trovo!!

**Comment by mrjacopong** [comment]
Risolto tutto fino al 31!

@roslaroc se trovi altro, apri una nuova issue per favore, così questo thread non diventa troppo lungo
