### ISSUE TITLE
last lesson issue

### ISSUE THREAD

**Issue by roslaroc** [mrjacopong/electromagnetic-compatibility#3]
1. eq.11.5: manca il cos(theta) dopo l/2 nell'esponenziale
![image](https://user-images.githubusercontent.com/16683342/118325991-950bb080-b504-11eb-8a92-e0a447fd6337.png)

2. eq.11.8,11.9: penso sia un * al posto del +
![image](https://user-images.githubusercontent.com/16683342/118326066-b8366000-b504-11eb-8bef-a084145ebb6f.png)

3. fig. 11.8: non mi torna la direzione delle frecce nel piano superiore (meglio discuterne insieme ahah)

**Comment by mrjacopong** [comment]
solved all ! grazie ros!
